name-template: "v$RESOLVED_VERSION ðŸŒˆ"
tag-template: "v$RESOLVED_VERSION"
template: |
  ## Changes

  $CHANGES
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
categories:
  - title: 'ðŸš€ Features'
    label: 'enhancement'
  - title: 'ðŸ› Bug Fixes'
    label: 'bug'
  - title: 'ðŸ“Œ Dependencies'
    label: 'dependencies'
version-resolver:
  major:
    labels: ["major"]
  minor:
    labels: ["minor"]
  patch:
    labels: ["patch"]
  default: patch
